name: ai_batch_gen
description: A Very Good Project created by Very Good CLI.
version: 0.0.1
repository: https://github.com/ChrisMarxDev/ai_batch_gen

environment:
  sdk: ^3.8.1

dependencies:
  args: ^2.7.0
  cli_completion: ^0.5.1
  mason_logger: ^0.3.3
  pub_updater: ^0.5.0
  yaml: ^3.1.2
  dotenv: ^4.2.0
  http: ^1.2.2
  retry: ^3.1.2
  path: ^1.9.0
  pool: ^1.5.2

dev_dependencies:
  build_runner: ^2.8.0
  build_verify: ^3.1.1
  build_version: ^2.1.3
  mocktail: ^1.0.4
  test: ^1.26.3
  very_good_analysis: any

executables:
  ai_batch_gen:
